require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - bin/bundle
    - bin/rspec
    - bin/rubocop


Layout/LineLength:
  Max: 80

# Layout/BeginEndAlignment:
#   EnforcedStyleAlignWith: start_of_line

# Layout/SpaceInsideHashLiteralBraces:
#   EnforcedStyle: "no_space"

# Layout/MultilineMethodCallIndentation:
#   EnforcedStyle: "indented_relative_to_receiver"

# Layout/HashAlignment:
#   EnforcedHashRocketStyle: "table"
#   EnforcedColonStyle: "key"

# Maybe this should be lower
# Metrics/AbcSize:
#   Max: 70

# Metrics/ClassLength:
#   Max: 600

# Metrics/CyclomaticComplexity:
#   Max: 15

# Metrics/ModuleLength:
#   Max: 400

# Metrics/MethodLength:
#   Max: 40

# Metrics/PerceivedComplexity:
#   Max: 15

# Metrics/BlockLength:
#   Max: 30

# Metrics/ParameterLists:
#   Max: 7

# Style/Documentation:
#   Exclude:
#     - 'spec/**/*'
#     - 'test/**/*'

# Style/SafeNavigationChainLength:
#   Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: "double_quotes"

# Style/SpecialGlobalVars:
#   EnforcedStyle: use_builtin_english_names

RSpec/ExampleLength:
  CountAsOne:
  - hash
  - array
  - heredoc
  Max: 20

# RSpec/MessageSpies:
#   EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 3

# RSpec/BeforeAfterAll:
#   Enabled: false
